# Generated by Django 5.2.11 on 2026-03-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['time']},
        ),
    ]
